"""add_encryption_fields_correct

Revision ID: 354420ba231b
Revises: 9e711bb01a81
Create Date: 2025-12-04 18:43:03.552374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354420ba231b'
down_revision = '9e711bb01a81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем поля для шифрования
    op.add_column('users', sa.Column('encryption_key', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('encryption_salt', sa.String(length=100), nullable=True))
    
    # Добавляем зашифрованные поля для HH API
    op.add_column('users', sa.Column('hh_client_id_encrypted', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('hh_client_secret_encrypted', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('hh_access_token_encrypted', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('hh_refresh_token_encrypted', sa.String(length=500), nullable=True))
    
    # Добавляем зашифрованные поля для LLM API
    op.add_column('users', sa.Column('llm_api_key_encrypted', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('llm_base_url_encrypted', sa.String(length=500), nullable=True))
    
    # Добавляем зашифрованные поля для контактной информации
    op.add_column('users', sa.Column('contact_email_encrypted', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('contact_phone_encrypted', sa.String(length=500), nullable=True))
    
    # Добавляем поле для хеша целостности данных
    op.add_column('users', sa.Column('data_integrity_hash', sa.String(length=200), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем поле для хеша целостности данных
    op.drop_column('users', 'data_integrity_hash')
    
    # Удаляем зашифрованные поля для контактной информации
    op.drop_column('users', 'contact_phone_encrypted')
    op.drop_column('users', 'contact_email_encrypted')
    
    # Удаляем зашифрованные поля для LLM API
    op.drop_column('users', 'llm_base_url_encrypted')
    op.drop_column('users', 'llm_api_key_encrypted')
    
    # Удаляем зашифрованные поля для HH API
    op.drop_column('users', 'hh_refresh_token_encrypted')
    op.drop_column('users', 'hh_access_token_encrypted')
    op.drop_column('users', 'hh_client_secret_encrypted')
    op.drop_column('users', 'hh_client_id_encrypted')
    
    # Удаляем поля для шифрования
    op.drop_column('users', 'encryption_salt')
    op.drop_column('users', 'encryption_key')
    
    # ### end Alembic commands ###