"""add_encryption_key_index

Revision ID: 73950ce113b6
Revises: fix_encryption_fields_complete
Create Date: 2025-12-05 23:50:24.864492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73950ce113b6'
down_revision = 'c73074b6ef35'  # <-- ПРОВЕРЬТЕ ЭТУ СТРОКУ! Должен быть ID предыдущей миграции
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Добавляем недостающее поле encryption_key
    op.add_column('users', sa.Column('encryption_key', sa.String(length=500), nullable=True))
    
    # 2. Создаем индекс для этого поля
    op.create_index('ix_users_encryption_key', 'users', ['encryption_key'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Удаляем индекс
    op.drop_index('ix_users_encryption_key', table_name='users')
    
    # 2. Удаляем поле (опционально, можно оставить для сохранения данных)
    op.drop_column('users', 'encryption_key')
    
    # ### end Alembic commands ###