"""add_user_columns

Revision ID: 9e711bb01a81
Revises: add_responses_tables
Create Date: 2025-12-04 16:14:07.807181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e711bb01a81'
down_revision = 'add_responses_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cover_letters_user_id', table_name='cover_letters')
    op.drop_index('ix_cover_letters_vacancy_id', table_name='cover_letters')
    op.drop_index('ix_generated_resumes_user_id', table_name='generated_resumes')
    op.drop_index('ix_generated_resumes_vacancy_id', table_name='generated_resumes')
    op.add_column('users', sa.Column('hh_access_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('hh_refresh_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('hh_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hh_token_expires')
    op.drop_column('users', 'hh_refresh_token')
    op.drop_column('users', 'hh_access_token')
    op.create_index('ix_generated_resumes_vacancy_id', 'generated_resumes', ['vacancy_id'], unique=False)
    op.create_index('ix_generated_resumes_user_id', 'generated_resumes', ['user_id'], unique=False)
    op.create_index('ix_cover_letters_vacancy_id', 'cover_letters', ['vacancy_id'], unique=False)
    op.create_index('ix_cover_letters_user_id', 'cover_letters', ['user_id'], unique=False)
    # ### end Alembic commands ###