"""Add hh_encryption_key column

Revision ID: c73074b6ef35
Revises: 354420ba231b
Create Date: 2025-12-04 19:58:29.253113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73074b6ef35'
down_revision = '354420ba231b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hh_encryption_key', sa.String(length=100), nullable=True))
    op.drop_index('ix_users_encryption_key', table_name='users')
    op.drop_column('users', 'hh_access_token_encrypted')
    op.drop_column('users', 'encryption_key')
    op.drop_column('users', 'contact_phone_encrypted')
    op.drop_column('users', 'contact_email_encrypted')
    op.drop_column('users', 'llm_base_url_encrypted')
    op.drop_column('users', 'hh_access_token')
    op.drop_column('users', 'hh_refresh_token_encrypted')
    op.drop_column('users', 'hh_refresh_token')
    op.drop_column('users', 'llm_api_key_encrypted')
    op.drop_column('users', 'encryption_salt')
    op.drop_column('users', 'data_integrity_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data_integrity_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('encryption_salt', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('llm_api_key_encrypted', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hh_refresh_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hh_refresh_token_encrypted', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hh_access_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('llm_base_url_encrypted', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('contact_email_encrypted', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('contact_phone_encrypted', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('encryption_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hh_access_token_encrypted', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_index('ix_users_encryption_key', 'users', ['encryption_key'], unique=False)
    op.drop_column('users', 'hh_encryption_key')
    # ### end Alembic commands ###