"""Update tables

Revision ID: 2aeef0326b2a
Revises: c11046bb1953
Create Date: 2025-12-01 23:16:00.529007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aeef0326b2a'
down_revision = 'c11046bb1953'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###