"""Update tables

Revision ID: c11046bb1953
Revises: e9d9aa42d653
Create Date: 2025-11-28 18:24:30.684335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11046bb1953'
down_revision = 'e9d9aa42d653'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###